image: archlinux
packages:
  - cmake
  - make
  - clang
  - lua
  - openssl
  - libevent
  - pcre2
sources:
  - https://git.sr.ht/~panda-roux/MoonGem
artifacts:
  - moongem.tar.xz
  - MOONGEM_SHA512SUM
tasks:
  - setup: |
      export CC=clang
      echo $(date -R) > TIMESTAMP
      mkdir build
  - build: |
      cd build
      cmake -DCMAKE_BUILD_TYPE=RelMinSize ../MoonGem
      make -j moongem
      strip --strip-unneeded moongem
  - compress: |
      cp build/moongem .
      tar -cJf moongem.tar.xz moongem TIMESTAMP
  - checksum: |
      sha512sum moongem.tar.xz > MOONGEM_SHA512SUM

